// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AbrirEmailNoOutlook(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AdicionarAssinatura():Promise<main.AssinaturaDTO>;

export function AplicarAtualizacao():Promise<void>;

export function ApresentacaoContarPaginas(arg1:string):Promise<number>;

export function ApresentacaoRenderizarPagina(arg1:string,arg2:number):Promise<string>;

export function AtualizarCadeiaICP():Promise<main.InfoCadeiaDTO>;

export function CarregarApresentacao():Promise<main.ApresentacaoDTO>;

export function CarregarBaseClientes():Promise<main.BaseClientesDTO>;

export function CarregarModelo():Promise<string>;

export function CarregarModeloFestas():Promise<string>;

export function CategoriasEmail():Promise<main.CatalogoEmailDTO>;

export function CopiarMensagem(arg1:string,arg2:string):Promise<main.ProcessamentoDTO>;

export function CopiarMensagemFestas(arg1:string,arg2:string):Promise<main.ProcessamentoDTO>;

export function CopiarTexto(arg1:string):Promise<void>;

export function CriarPDFDeImagens(arg1:Array<main.PaginaPDFEditadaDTO>):Promise<string>;

export function EnviarWhatsApp(arg1:string,arg2:string):Promise<main.ProcessamentoDTO>;

export function EnviarWhatsAppFestas(arg1:string,arg2:string):Promise<main.ProcessamentoDTO>;

export function EscolherApresentacao():Promise<main.ApresentacaoDTO>;

export function EscolherArquivosAssinatura():Promise<Array<string>>;

export function EscolherPDFParaEditar():Promise<string>;

export function EscolherPasta():Promise<main.PastaDTO>;

export function EstadoInicial():Promise<main.InicioDTO>;

export function ExportarCSV():Promise<string>;

export function GerarEmail(arg1:string,arg2:string,arg3:Array<main.ItemEmailEntrada>,arg4:string):Promise<string>;

export function LimparFestasEnviados():Promise<main.ProcessamentoDTO>;

export function LimparTudo():Promise<main.ProcessamentoDTO>;

export function ListarAssinaturas():Promise<Array<main.AssinaturaDTO>>;

export function ObterAssinaturaAtiva():Promise<main.AssinaturaDTO>;

export function ObterImagemGrafico(arg1:string):Promise<string>;

export function ObterInfoCadeiaICP():Promise<main.InfoCadeiaDTO>;

export function ObterPreviaPaginaGraficoRentabilidade(arg1:string):Promise<string>;

export function PreencherTypeform(arg1:Array<main.ItemRespostaTypeformDTO>):Promise<void>;

export function ProcessarPastaAtual():Promise<main.ProcessamentoDTO>;

export function RemoverApresentacao():Promise<void>;

export function RemoverAssinatura(arg1:string):Promise<void>;

export function RestaurarRecorteGraficoPadrao():Promise<void>;

export function SalvarDadosAssessor(arg1:string,arg2:string):Promise<void>;

export function SalvarEmailRemetente(arg1:string):Promise<void>;

export function SalvarImagemPNG(arg1:string):Promise<string>;

export function SalvarModelo(arg1:string):Promise<void>;

export function SalvarModeloFestas(arg1:string):Promise<void>;

export function SalvarPDFEditado(arg1:Array<main.PaginaPDFEditadaDTO>,arg2:string):Promise<string>;

export function SalvarPreferencias(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean,arg8:boolean,arg9:Array<string>,arg10:Array<string>):Promise<void>;

export function SalvarRecorteGraficoRentabilidade(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function SalvarTypeform(arg1:string,arg2:string):Promise<string>;

export function SelecionarAssinaturaAtiva(arg1:string):Promise<void>;

export function ValidarAssinaturaICP(arg1:Array<string>):Promise<main.ResultadoValidacaoDTO>;

export function VerificarAtualizacao():Promise<main.AtualizacaoDTO>;

export function VersaoAtual():Promise<string>;
