// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbrirEmailNoOutlook(arg1, arg2, arg3) {
  return window['go']['main']['App']['AbrirEmailNoOutlook'](arg1, arg2, arg3);
}

export function AdicionarAssinatura() {
  return window['go']['main']['App']['AdicionarAssinatura']();
}

export function AplicarAtualizacao() {
  return window['go']['main']['App']['AplicarAtualizacao']();
}

export function ApresentacaoContarPaginas(arg1) {
  return window['go']['main']['App']['ApresentacaoContarPaginas'](arg1);
}

export function ApresentacaoRenderizarPagina(arg1, arg2) {
  return window['go']['main']['App']['ApresentacaoRenderizarPagina'](arg1, arg2);
}

export function AtualizarCadeiaICP() {
  return window['go']['main']['App']['AtualizarCadeiaICP']();
}

export function CarregarApresentacao() {
  return window['go']['main']['App']['CarregarApresentacao']();
}

export function CarregarBaseClientes() {
  return window['go']['main']['App']['CarregarBaseClientes']();
}

export function CarregarModelo() {
  return window['go']['main']['App']['CarregarModelo']();
}

export function CarregarModeloFestas() {
  return window['go']['main']['App']['CarregarModeloFestas']();
}

export function CategoriasEmail() {
  return window['go']['main']['App']['CategoriasEmail']();
}

export function CopiarMensagem(arg1, arg2) {
  return window['go']['main']['App']['CopiarMensagem'](arg1, arg2);
}

export function CopiarMensagemFestas(arg1, arg2) {
  return window['go']['main']['App']['CopiarMensagemFestas'](arg1, arg2);
}

export function CopiarTexto(arg1) {
  return window['go']['main']['App']['CopiarTexto'](arg1);
}

export function CriarPDFDeImagens(arg1) {
  return window['go']['main']['App']['CriarPDFDeImagens'](arg1);
}

export function EnviarWhatsApp(arg1, arg2) {
  return window['go']['main']['App']['EnviarWhatsApp'](arg1, arg2);
}

export function EnviarWhatsAppFestas(arg1, arg2) {
  return window['go']['main']['App']['EnviarWhatsAppFestas'](arg1, arg2);
}

export function EscolherApresentacao() {
  return window['go']['main']['App']['EscolherApresentacao']();
}

export function EscolherArquivosAssinatura() {
  return window['go']['main']['App']['EscolherArquivosAssinatura']();
}

export function EscolherPDFParaEditar() {
  return window['go']['main']['App']['EscolherPDFParaEditar']();
}

export function EscolherPasta() {
  return window['go']['main']['App']['EscolherPasta']();
}

export function EstadoInicial() {
  return window['go']['main']['App']['EstadoInicial']();
}

export function ExportarCSV() {
  return window['go']['main']['App']['ExportarCSV']();
}

export function GerarEmail(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GerarEmail'](arg1, arg2, arg3, arg4);
}

export function LimparFestasEnviados() {
  return window['go']['main']['App']['LimparFestasEnviados']();
}

export function LimparTudo() {
  return window['go']['main']['App']['LimparTudo']();
}

export function ListarAssinaturas() {
  return window['go']['main']['App']['ListarAssinaturas']();
}

export function ObterAssinaturaAtiva() {
  return window['go']['main']['App']['ObterAssinaturaAtiva']();
}

export function ObterImagemGrafico(arg1) {
  return window['go']['main']['App']['ObterImagemGrafico'](arg1);
}

export function ObterInfoCadeiaICP() {
  return window['go']['main']['App']['ObterInfoCadeiaICP']();
}

export function ObterPreviaPaginaGraficoRentabilidade(arg1) {
  return window['go']['main']['App']['ObterPreviaPaginaGraficoRentabilidade'](arg1);
}

export function Plataforma() {
  return window['go']['main']['App']['Plataforma']();
}

export function PreencherTypeform(arg1) {
  return window['go']['main']['App']['PreencherTypeform'](arg1);
}

export function ProcessarPastaAtual() {
  return window['go']['main']['App']['ProcessarPastaAtual']();
}

export function RemoverApresentacao() {
  return window['go']['main']['App']['RemoverApresentacao']();
}

export function RemoverAssinatura(arg1) {
  return window['go']['main']['App']['RemoverAssinatura'](arg1);
}

export function RestaurarRecorteGraficoPadrao() {
  return window['go']['main']['App']['RestaurarRecorteGraficoPadrao']();
}

export function SalvarDadosAssessor(arg1, arg2) {
  return window['go']['main']['App']['SalvarDadosAssessor'](arg1, arg2);
}

export function SalvarEmailRemetente(arg1) {
  return window['go']['main']['App']['SalvarEmailRemetente'](arg1);
}

export function SalvarImagemPNG(arg1) {
  return window['go']['main']['App']['SalvarImagemPNG'](arg1);
}

export function SalvarModelo(arg1) {
  return window['go']['main']['App']['SalvarModelo'](arg1);
}

export function SalvarModeloFestas(arg1) {
  return window['go']['main']['App']['SalvarModeloFestas'](arg1);
}

export function SalvarPDFEditado(arg1, arg2) {
  return window['go']['main']['App']['SalvarPDFEditado'](arg1, arg2);
}

export function SalvarPreferencias(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['SalvarPreferencias'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function SalvarRecorteGraficoRentabilidade(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SalvarRecorteGraficoRentabilidade'](arg1, arg2, arg3, arg4);
}

export function SalvarTypeform(arg1, arg2) {
  return window['go']['main']['App']['SalvarTypeform'](arg1, arg2);
}

export function SelecionarAssinaturaAtiva(arg1) {
  return window['go']['main']['App']['SelecionarAssinaturaAtiva'](arg1);
}

export function ValidarAssinaturaICP(arg1) {
  return window['go']['main']['App']['ValidarAssinaturaICP'](arg1);
}

export function VerificarAtualizacao() {
  return window['go']['main']['App']['VerificarAtualizacao']();
}

export function VersaoAtual() {
  return window['go']['main']['App']['VersaoAtual']();
}
